Seblatre/scmtag
cecom/pomutils pull request #12
Opened 2018-11-15 06:36 UTC by seblatre

Fix #11 .

2019-02-27 08:34 UTC, cecom requested changes
And plz rebase on develop branch and choose as target develop in the pull request.

Otherwise it looks good 👍

2019-02-27 08:34 UTC, cecom commented on src/test/resources/rulesets/rulesetScmTag/ourStrategy/our.pom.xml
> +    <tag>base</tag>
```suggestion
    <tag>our</tag>
```

2019-02-27 08:34 UTC, cecom commented on src/test/resources/rulesets/rulesetScmTag/ourStrategy/their.pom.xml
> +    <tag>base</tag>
```suggestion
    <tag>their</tag>
```

2019-02-27 08:34 UTC, cecom commented on src/test/resources/rulesets/rulesetScmTag/theirStrategy/our.pom.xml
> +    <tag>base</tag>
```suggestion
    <tag>our</tag>
```

2019-02-27 08:34 UTC, cecom commented on src/test/resources/rulesets/rulesetScmTag/theirStrategy/their.pom.xml
> +    <tag>base</tag>
```suggestion
    <tag>their</tag>
```

2019-03-05 10:25 UTC, seblatre commented
@cecom, sorry I'm new to github, I'm learning ^^
Hope this is right now.

2019-03-15 07:33 UTC, cecom reviewed
looks good

2019-03-15 07:34 UTC, merged